version: '3.8'

services:

  web:
    build: .
    image: web
    container_name: web
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    command: gunicorn --bind 0.0.0.0:${APPLICATION_PORT} main:main_app --workers 4
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    command: celery --app tasks.image_validator_task.celery_utility worker --loglevel=info --logfile=application.log
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  dashboard:
    build: .
    command: celery --app tasks.image_validator_task.celery_utility flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5556:5555
    environment:
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379